#
# node.js container
#
from quarry/base
maintainer Kai Davenport
run apt-get install -y python-software-properties make
run add-apt-repository -y ppa:chris-lea/node.js
run apt-get update
run apt-get install -y nodejs