from ubuntu
MAINTAINER Kai Davenport
run echo "test"
run	echo "deb http://archive.ubuntu.com/ubuntu precise main universe" > /etc/apt/sources.list
run	apt-get -y update
run	apt-get -y install git make supervisor