#!/bin/bash

sed -i 's/docker -d$/docker -d -r=true/' /etc/init/docker.conf

echo $HOSTNAME > /home/git/HOSTNAME


# temporary hack for https://github.com/progrium/dokku/issues/82
# redeploys all apps after a reboot
cat<<EOF > /etc/init/quarry-redeploy.conf
description "quarry app redeploy service"

start on (started docker)

script
  sleep 2 # give docker some time
  sudo -i -u git /usr/local/bin/quarry deploy:all
end script
EOF

