#!/usr/bin/env bash
set -eo pipefail; [[ $QUARRY_TRACE ]] && set -x

case "$1" in

  # stop all services for a stack
  services:stop)
    STACK="$2";
    if [[ -z $STACK ]]; then
      echo "usage quarry services:stop <stack>"
      exit 1;
    fi
    STACK_DIR="$QUARRY_ROOT/$STACK";
    DEPLOY_DIR="$STACK_DIR/db/service";

    for servicefolder in $DEPLOY_DIR/* ; do
      cid=`cat $servicefolder/id`
      docker stop $cid
    done
    ;;

  # start all services for a stack
  services:start)
    STACK="$2";
    if [[ -z $STACK ]]; then
      echo "usage quarry services:stop <stack>"
      exit 1;
    fi
    STACK_DIR="$QUARRY_ROOT/$STACK";
    DEPLOY_DIR="$STACK_DIR/db/service";

    for servicefolder in $DEPLOY_DIR/* ; do
      cid=`cat $servicefolder/id`
      docker start $cid
    done
    ;;

  # kill all services for a stack
  services:kill)
    STACK="$2";
    if [[ -z $STACK ]]; then
      echo "usage quarry services:kill <stack>"
      exit 1;
    fi
    STACK_DIR="$QUARRY_ROOT/$STACK";
    DEPLOY_DIR="$STACK_DIR/db/service";

    for servicefolder in $DEPLOY_DIR/* ; do
      cid=`cat $servicefolder/id`
      docker kill $cid
      docker rm $cid
      rm -rf $servicefolder
    done
    ;;

  help)
    cat
    ;;

esac
