#!/bin/bash
#
#	a script that downloads and builds the quarry docker files
#
set -e
export QUARRYFILES_URL=${QUARRYFILES_URL:-https://github.com/binocarlos/quarryfiles}
export QUARRYFILES_IMAGES=( "hipache" "mongo" "redis" "node" )

# check that we have docker installed
#test -n `docker version` || echo "docker must be installed" 1>&2 && exit;
docker version >/dev/null 2>&1 || { echo >&2 "I require docker but it's not installed.  Aborting."; exit 1; }
# build a single docker file
function install_image {
	# we surpress output for the hipache container cos it breaks otherwise
	flags=""
	if [ "$1" = 'hipache' ]; then
		flags=" -q"
	fi
	echo "building image $1"
	docker build $flags -t quarry/$1 ~/quarryfiles/$1
}

# make sure the Dockerfiles are downloaded
if [ ! -d ~/quarryfiles ]
then
	echo "cloning images repo"
	cd ~ && git clone $QUARRYFILES_URL	
else
	echo "pull images repo"
	cd ~/quarryfiles && git pull
fi

case "$1" in
  all)
		# check for the install folder otherwise clone & build
		for IMAGE in "${QUARRYFILES_IMAGES[@]}"
		do
		  install_image $IMAGE
		done
		;;

	*)
		install_image $1
		;;
esac

