#!/usr/bin/env bash
set -eo pipefail; [[ $QUARRY_TRACE ]] && set -x

case "$1" in

  testbuild)
    APP="$2";
    SOURCE_FOLDER=`pwd`
    tar --exclude=.git -c . | quarry receive $APP
    ;;

  help)
    cat && cat<<EOF
    testbuild <stackname>                        Run the local folder without a git push
EOF
    ;;

esac
